# Generated by Django 5.1.6 on 2025-03-03 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PIDLoop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('loop_type', models.CharField(choices=[('first_order', 'First Order'), ('integrator', 'Integrator'), ('integrator_lag', 'Integrator with Lag')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PIDCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proportional_gain', models.FloatField()),
                ('integral_time', models.FloatField()),
                ('derivative_time', models.FloatField()),
                ('acceptable_filter_time', models.FloatField()),
                ('pid_loop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pid_calculation', to='tuner.pidloop')),
            ],
        ),
        migrations.CreateModel(
            name='LambdaVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lambda_value', models.FloatField()),
                ('min_lambda', models.FloatField()),
                ('max_lambda', models.FloatField()),
                ('pid_loop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lambda_variable', to='tuner.pidloop')),
            ],
        ),
        migrations.CreateModel(
            name='TrendChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='trend_charts/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pid_loop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_charts', to='tuner.pidloop')),
            ],
        ),
    ]
