# Generated by Django 5.1.6 on 2025-03-03 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BumpTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('pid_loop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuner.pidloop')),
            ],
        ),
    ]
