# Generated by Django 5.1.6 on 2025-03-03 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuner', '0002_bumptest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bumptest',
            name='pid_loop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bump_tests', to='tuner.pidloop'),
        ),
    ]
