# Generated by Django 5.1.6 on 2025-03-04 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuner', '0003_alter_bumptest_pid_loop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendchart',
            name='csv_file',
        ),
        migrations.AddField(
            model_name='trendchart',
            name='file',
            field=models.FileField(default='', upload_to='trends/'),
        ),
        migrations.AddField(
            model_name='trendchart',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trendchart',
            name='pid_loop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuner.pidloop'),
        ),
    ]
