# Generated by Django 5.1.6 on 2025-03-04 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuner', '0004_remove_trendchart_csv_file_trendchart_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bumptest',
            name='pid_loop',
        ),
        migrations.RemoveField(
            model_name='pidloop',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pidloop',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pidloop',
            name='loop_type',
        ),
        migrations.RemoveField(
            model_name='trendchart',
            name='name',
        ),
        migrations.AddField(
            model_name='bumptest',
            name='trend_chart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tuner.trendchart'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pidloop',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trendchart',
            name='file',
            field=models.FileField(upload_to='trend_charts/'),
        ),
    ]
