# Generated by Django 5.1.6 on 2025-03-04 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuner', '0005_remove_bumptest_pid_loop_remove_pidloop_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bumptest',
            name='trend_chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bump_tests', to='tuner.trendchart'),
        ),
    ]
